src/Entity/Devis.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\DevisRepository;
use App\Entity\Trait\CreatedAtTrait;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\HttpFoundation\File\File;

#[ORM\Entity(repositoryClass: DevisRepository::class)]
class Devis
{
    use CreatedAtTrait;
    
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $comment = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $image_object = null;

    #[ORM\Column(options: ['default' => false])]
    private ?bool $status = false;

    #[ORM\ManyToOne(inversedBy: 'devis')]
    private ?User $User = null;

    #[ORM\ManyToOne(inversedBy: 'devis')]
    private ?TypeOperation $typeOperation = null;

    #[ORM\ManyToMany(targetEntity: Operation::class, inversedBy: 'devis')]
    private Collection $Operation;

    #[ORM\Column(length: 255)]
    private ?string $adresse_intervention = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $mail = null;

    #[ORM\Column(length: 12)]
    private ?string $tel = null;

    #[ORM\Column(nullable: true)]
    private ?float $tarif_custom = null;

    public function __construct()
    {
        $this->Operation = new ArrayCollection();
        $this->created_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): static
    {
        $this->comment = $comment;

        return $this;
    }

    public function getImageObject(): ?string
    {
        return $this->image_object;
    }

    public function setImageObject(?string $image_object): static
    {
        $this->image_object = $image_object;

        return $this;
    }

    public function isStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): static
    {
        $this->User = $User;

        return $this;
    }

    public function getTypeOperation(): ?TypeOperation
    {
        return $this->typeOperation;
    }

    public function setTypeOperation(?TypeOperation $typeOperation): static
    {
        $this->typeOperation = $typeOperation;

        return $this;
    }

    /**
     * @return Collection<int, Operation>
     */
    public function getOperation(): Collection
    {
        return $this->Operation;
    }

    public function addOperation(Operation $operation): static
    {
        if (!$this->Operation->contains($operation)) {
            $this->Operation->add($operation);
        }

        return $this;
    }

    public function removeOperation(Operation $operation): static
    {
        $this->Operation->removeElement($operation);

        return $this;
    }

    public function getAdresseIntervention(): ?string
    {
        return $this->adresse_intervention;
    }

    public function setAdresseIntervention(string $adresse_intervention): static
    {
        $this->adresse_intervention = $adresse_intervention;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): static
    {
        $this->mail = $mail;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): static
    {
        $this->tel = $tel;

        return $this;
    }

    public function getTarifCustom(): ?float
    {
        return $this->tarif_custom;
    }

    public function setTarifCustom(?float $tarif_custom): static
    {
        $this->tarif_custom = $tarif_custom;

        return $this;
    }
}

src/Controller/DevisController.php
<?php

namespace App\Controller;

use SplFileObject;
use App\Entity\User;
use App\Entity\Devis;
use Twig\Environment;
use App\Form\DevisType;
use App\Entity\Operation;
use App\Form\EditDevisType;
use App\Service\JWTService;
use App\Service\PdfService;
use App\Entity\TypeOperation;
use PhpParser\Node\Stmt\Catch_;
use App\Service\PostLogsService;
use App\Service\SendMailService;
use App\Repository\UserRepository;
use App\Repository\DevisRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Csrf\TokenGenerator\TokenGeneratorInterface;

#[Route('/admin/devis')]
class DevisController extends AbstractController
{

    private EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    #[Route('/', name: 'app_devis_index', methods: ['GET'])]
    public function index(DevisRepository $devisRepository): Response
    {
        $devis = $devisRepository->findAll();

        $devisWithTrueStatus = [];

        foreach ($devis as $devi) {
            if ($devi->isStatus() === true) {
                $devisWithTrueStatus[] = $devi->getId();
            }
        }

        return $this->render('devis/index.html.twig', [
            'devis' => $devis,
            'devisWithTrueStatus' => $devisWithTrueStatus,
        ]);
    }

    #[Route('/new', name: 'app_devis_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $devi = new Devis();
        $form = $this->createForm(DevisType::class, $devi);
        $form->handleRequest($request);

        // $type_operations = $entityManager->getRepository(TypeOperation::class)->findAll();

        if ($form->isSubmitted() && $form->isValid()) {

            $existingDevis = $entityManager->getRepository(Devis::class)->findOneBy([
                'mail' => $devi->getMail(),
                'typeOperation' => $devi->getTypeOperation(),
                'adresse_intervention' => $devi->getAdresseIntervention()
            ]);

            if ($existingDevis !== null) {
                $this->addFlash('warning', 'Ce devis existe déjà.');
                return $this->redirectToRoute('app_devis_new');
            }

            // $serv = $form->getData();
            $mail = $form->get('mail')->getData();
            $mailConfirmation = $form->get('mailConfirmation')->getData();

            if ($mail === $mailConfirmation) {

                if ($form->get('image_object')->getData() !== null) {
                    $photo = $form['image_object']->getData();
                    $fileName = uniqid().'.'.$photo->guessExtension();
                    $photo->move($this->getParameter('photo_dir'), $fileName);
                    $filePath = 'uploads/services/' . $fileName;
                    $devi->setImageObject($filePath);
                }
            
                $typeOperation = $devi->getTypeOperation();
            if ($typeOperation !== null) {
                    $tarifTypeOperation = $typeOperation->getTarif();
                    $devi->setTarifCustom($tarifTypeOperation);
                }

                    $entityManager->persist($devi);
                    $entityManager->flush();
            }else { 
                $this->addFlash('warning', 'Les mails ne correspondent pas');
                return $this->redirectToRoute('app_devis_new', [], Response::HTTP_SEE_OTHER);
            };

            return $this->redirectToRoute('app_devis_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('devis/new.html.twig', [
            'devi' => $devi,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}/toggle-status', name: 'app_devis_toggle_status', methods: ['POST'])]
    public function toggleStatus(Request $request, Devis $devi, EntityManagerInterface $entityManager, SendMailService $mail, JWTService $jwt, PostLogsService $postLogsService): Response
    {

        $currentUser = $this->getUser();

        if (in_array('ROLE_ADMIN', $currentUser->getRoles(), true)) {

            if ($currentUser->getOperationEnCours() >= 5) {

                return new Response('Vous avez déjà atteint le nombre maximum d\'opérations en cours.', Response::HTTP_FORBIDDEN);
            }
        } elseif (in_array('ROLE_SENIOR', $currentUser->getRoles(), true)) {

            if ($currentUser->getOperationEnCours() >= 3) {
                
                return new Response('Vous avez déjà atteint le nombre maximum d\'opérations en cours.', Response::HTTP_FORBIDDEN);
            }
        } elseif (in_array('ROLE_APPRENTI', $currentUser->getRoles(), true)) {

            if ($currentUser->getOperationEnCours() >= 1) {
                
                return new Response('Vous avez déjà atteint le nombre maximum d\'opérations en cours.', Response::HTTP_FORBIDDEN);
            }
        }

        if ($request->request->has('status')) {

            $status = $request->request->get('status');
            
            if ($status === 'true') {
                
                $currentUser->setOperationEnCours(($currentUser->getOperationEnCours() ?? 0) + 1);
                $entityManager->persist($currentUser);
                $existingUser = $entityManager->getRepository(User::class)->findOneByEmail($devi->getMail());

                if ($existingUser) {
                    
                    $devi->setUser($existingUser);
                } else {

                $user = new User();

                $user->setFirstname($devi->getFirstname());
                $user->setLastname($devi->getLastname());
                $user->setEmail($devi->getMail());
                $user->setRoles(["ROLE_CLIENT"]);
                $user->setAddress($devi->getAdresseIntervention());
                $user->setTel($devi->getTel());
              
                $entityManager->persist($user);
                $entityManager->flush();

                $devi->setUser($user);

                $header =[
                    'typ'=>'JWT',
                    'alg'=>'HS256'
                ];

                $payload =[
                    'user_id'=>$user->getId()
                ];

                $token = $jwt->generate($header,$payload,
                $this->getParameter('app.jwtsecret'));
    
                $mail->send ('no-reply@cleanthis.fr',
                    $user->getEmail(),
                    'Activation de votre compte CleanThis',
                    'register',
                    compact('user','token')
                );

                $postLogsService->postConnexionInfos(
                    'devisApp',
                    'Un devis a été validé',
                    'Info',
                    [],
                    $user->getEmail()
    
                );

            }
            $operation = new Operation();

            $operation->setUser($currentUser);
            
            $devi->addOperation($operation);

            $devi->setStatus(true);
            $entityManager->persist($operation);
            $entityManager->persist($devi);
            $entityManager->flush();

        }
            
        }

        return $this->redirectToRoute('app_devis_index');
    }

    #[Route('/{id}', name: 'app_devis_show', methods: ['GET'])]
    public function show(Devis $devi): Response
    {
        return $this->render('devis/show.html.twig', [
            'devi' => $devi,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_devis_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Devis $devi, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EditDevisType::class, $devi);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            // if ($form->get('image_object')->getData() !== null) {
            //     $photo = $form['image_object']->getData();
            //     $fileName = uniqid().'.'.$photo->guessExtension();
            //     $photo->move($this->getParameter('photo_dir'), $fileName);
            //     $file = new File($this->getParameter('photo_dir').'/'.$fileName);
            //     $devi->setImageObject($file);
            // }
            
            $entityManager->flush();

            return $this->redirectToRoute('app_devis_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('devis/edit.html.twig', [
            'devi' => $devi,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_devis_delete', methods: ['POST'])]
    public function delete(Request $request, Devis $devi, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$devi->getId(), $request->request->get('_token'))) {
            $user = $devi->getUser();
            if ($user !== null) {
                $entityManager->remove($user);
            }
            
            // Supprimer le devis
            $entityManager->remove($devi);
            $entityManager->flush();

            return new JsonResponse(['success' => true]);
        }

        return new JsonResponse(['success' => false]);
    }
   
    #[Route('/pdf/{id}', name: 'devis_pdf', methods: ['GET'])]
    public function generatePdfDevis(PdfService $pdf, Devis $devi = null, EntityManagerInterface $entityManager): Response
    {
        $id_operation = $devi->getTypeOperation();

templates/devis/_delete_form.html.twig
<form method="post" action="{{ path('app_devis_delete', {'id': devi.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ devi.id) }}">
    <button class="btn">Delete</button>
</form>

templates/devis/_editForm.html.twig
{% block body %}
	<section class="home1">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 mt-5">
					<div class="card">
						<div class="card-header">
							<h2 class="text-center">Modification de devis</h2>
						</div>
						<div class="card-body">
							{{ form_start(form) }}
							<div class="row">
								<div class="col-md-6">
									{{ form_row(form.tarif_custom) }}
								</div>

								{{ form_row(form.comment) }}
								<div style="margin-top:15px;">
								<button style="float:right;" class="btn btn-primary">Modifier le devis</button>
								<a style="float:left;" href="{{ path('app_devis_index') }}" class="retour">← Retour à la liste</a>
								</div>
								{{ form_end(form) }}

							</div>
						</div>
					</div>
				</div>
			</div>
		</section>

		<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
		<script>
			$(document).ready(function () {
$('#image-object-field').hide();

$('.type-operation-select').change(function () {
console.log('Nouvelle valeur sélectionnée :', $(this).val());
var selectedOptionLabel = $(this).find('option:selected').text().toLowerCase();
var keyword = 'custom';
if (selectedOptionLabel.indexOf(keyword.toLowerCase()) !== -1) {
console.log('Option contenant "Custom" sélectionnée');
$('#image-object-field').show();
} else {
console.log('Autre option sélectionnée');
$('#image-object-field').hide();
}
});
});
		</script>
	{% endblock %}

templates/devis/_form.html.twig
{% block body %}
<section class="home1">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 mt-5">
                <div class="card">
                    <div class="card-header">
                        <h2 class="text-center">Création de devis</h2>
                    </div>
                    <div class="card-body">
                        {{ form_start(form) }}
                        <div class="row">
                            <div class="col-md-6">
                                {{ form_row(form.lastname) }}
                            </div>
                            <div class="col-md-6">
                                {{ form_row(form.firstname) }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                {{ form_row(form.mail) }}
                            </div>
                            <div class="col-md-6">
                                {{ form_row(form.mailConfirmation) }}
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                {{ form_row(form.tel) }}
                            </div>
                            <div class="col-md-6">
                                {{ form_row(form.adresse_intervention, {'attr': {'class': 'form-control adresse-autocomplete', 'style': 'margin-top: 5px; margin-bottom: 5px;'}}) }}
                            </div>
                        </div>
                        <div style="margin-left: 25%" class="col-md-6">
                            <div class="d-flex align-items-center">
                                {{ form_row(form.Type_Operation) }}
                            </div>
                        </div>
                        <div id="image-object-field" style="display: none;">
                            {{ form_row(form.image_object) }}
                        </div>
                        {{ form_row(form.comment) }}

							<button class="btn1 btn-primary">Envoi devis</button>
							{{ form_end(form) }}
                            

						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script>
		$(document).ready(function () {
$('#image-object-field').hide();

$('.type-operation-select').change(function () {
console.log('Nouvelle valeur sélectionnée :', $(this).val());
var selectedOptionLabel = $(this).find('option:selected').text().toLowerCase();
var keyword = 'custom';
if (selectedOptionLabel.indexOf(keyword.toLowerCase()) !== -1) {
console.log('Option contenant "Custom" sélectionnée');
$('#image-object-field').show();
} else {
console.log('Autre option sélectionnée');
$('#image-object-field').hide();
}
});
});
	</script>
{% endblock %}
{% block javascripts %}
    {# <script>
    document.addEventListener('DOMContentLoaded', function() {
        var adresseInput = document.querySelector('.adresse-autocomplete');

        if (!adresseInput) return;

        function performSearchAndUpdateAdresse(query) {
            var suggestionsContainer = document.createElement('div');
            suggestionsContainer.className = 'suggestions-container';

            fetch(`https://api-adresse.data.gouv.fr/search/?q=${encodeURIComponent(query)}&limit=5`)
                .then(response => response.json())
                .then(data => {
                    suggestionsContainer.innerHTML = '';

                    data.features.forEach((feature) => {
                        var suggestion = document.createElement('div');
                        suggestion.className = 'suggestion';
                        suggestion.innerText = feature.properties.label;

                        suggestion.addEventListener('click', function() {
                            adresseInput.value = feature.properties.label;
                            suggestionsContainer.innerHTML = '';
                        });

                        suggestionsContainer.appendChild(suggestion);
                    });
                })
                .catch(error => console.error('Erreur API:', error));
        }

        // Écouter les événements de saisie sur le champ adresse_intervention
        adresseInput.addEventListener('input', function() {
            var query = adresseInput.value;
            if (query.length < 3) return; // Éviter les requêtes trop fréquentes
            performSearchAndUpdateAdresse(query);
        });

        adresseInput.parentNode.appendChild(suggestionsContainer);
    });
</script> #}

{% endblock %}

templates/devis/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block stylesheets %} 
    {{ parent() }} {# Inclut les feuilles de style du fichier parent #}
    <link rel="stylesheet" href="{{ asset('public/assets/css/style.css') }}">
{% endblock %}

{% block body %}
  <section class="home">
    <div class="text">
    
    <h1>Edit devis</h1>


    {{ include('devis/_editForm.html.twig', {'button_label': 'Update'}) }}

    

    </div>
   </section> 
{% endblock %}

templates/devis/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Devis{% endblock %}
{% block stylesheets %} 
    {{ parent() }} {# Inclut les feuilles de style du fichier parent #}
    <link rel="stylesheet" href="{{ asset('assets/css/devis.css') }}">
{% endblock %}

{% block body %}
<section class='home'>
<div class='text'>
    <h1>Create new Devis</h1>

    {{ include('devis/_form.html.twig') }}
    <a class="backtolist1" href="{{ path('app_devis_index') }}">Retour à la liste</a>

    <script src="{{ asset('assets/js/autocompleteDevis.js') }}"> defer</script>
</div>
</section>
{% endblock %}

templates/devis/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Devis{% endblock %}

{% block body %}
<section class='home'>
    <div class='text'>
    {# <div class="container" style="padding-top: 100px; margin-left: 300px"> #}
        <div>
            <div class="row gutters-sm">
                <div class="col-md-4 mb-3 pt-5">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex flex-column align-items-center text-center">
                                <h4>{{ devi.id }}</h4>
                                <div class="mt-3">
                                    <p class="text-secondary mb-1">Créé le :</p>
                                    <p class="text-muted font-size-sm">{{ devi.createdAt ? devi.createdAt|date('d-m-Y H:i:s') : '' }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-8 pt-5">
                    <div class="card mb-3 ">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">ID</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{ devi.id }}
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Nom</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{ devi.lastname }}
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Prenom</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{ devi.firstname }}
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Tarif</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{ devi.tarifCustom }}€
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Commentaires</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{ devi.comment }}
                                </div>
                            </div>
                            <hr>    
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Statut</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{ devi.status ? 'Yes' : 'No' }}
                                </div>
                            </div>      
                                    {% if devi.imageObject %}
                                    <hr>
                                    <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Image_object</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                    <div id="imageContainer" style="cursor: pointer;">Cliquez pour agrandir l'image</div>
                                    <script>
                                        document.getElementById("imageContainer").addEventListener("click", function() {
                                            var imageUrl = "{{ asset(devi.imageObject) }}";
                                            var enlargedImage = document.createElement("img");
                                            enlargedImage.src = imageUrl;
                                            enlargedImage.alt = "Image agrandie";
                                            enlargedImage.style.maxWidth = "100%";
                                            var overlay = document.createElement("div");
                                            overlay.style.position = "fixed";
                                            overlay.style.top = "0";
                                            overlay.style.left = "0";
                                            overlay.style.width = "100%";
                                            overlay.style.height = "100%";
                                            overlay.style.backgroundColor = "rgba(0, 0, 0, 0.7)";
                                            overlay.style.display = "flex";
                                            overlay.style.justifyContent = "center";
                                            overlay.style.alignItems = "center";
                                            overlay.appendChild(enlargedImage);
                                            document.body.appendChild(overlay);
                                            overlay.addEventListener("click", function() {
                                                document.body.removeChild(overlay);
                                            });
                                        });
                                    </script>
                                </div>
                                 {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <a href="{{ path('app_devis_index') }}" class= "retour">← Retour à la liste</a>
        </div>
    {# </div> #}
    </div>
</section>
{% endblock %}