src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Trait\CreatedAtTrait;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Nullable;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    use CreatedAtTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column(nullable:true)]
    private ?string $password = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $google_id = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $avatar = null;

    #[ORM\Column(length: 60)]
    private ?string $lastname = null;

    #[ORM\Column(length: 60)]
    private ?string $firstname = null;

    #[ORM\Column(nullable:true ,length: 14)]
    private ?string $tel = null;

    #[ORM\Column(nullable: true)]
    private ?int $operations_finalisee = null;

    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    private $resetToken;

    #[ORM\OneToMany(targetEntity: Devis::class, mappedBy: 'User')]
    private Collection $devis;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address = null;

    #[ORM\Column(type: 'boolean')]
    private $is_verified = false;

    #[ORM\Column(nullable: true)]
    private ?int $operation_en_cours = null;

    #[ORM\OneToMany(targetEntity: Operation::class, mappedBy: 'user')]

    private Collection $operations;

    public function __construct()
    {
        $this->devis = new ArrayCollection();
        $this->created_at = new \DateTimeImmutable();
        $this->operations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getGoogleId(): ?string
    {
        return $this->google_id;
    }

    public function setGoogleId(?string $google_id): static
    {
        $this->google_id = $google_id;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): static
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): static
    {
        $this->tel = $tel;

        return $this;
    }

    public function getOperationsFinalisee(): ?int
    {
        return $this->operations_finalisee;
    }

    public function setOperationsFinalisee(?int $operations_finalisee): static
    {
        $this->operations_finalisee = $operations_finalisee;

        return $this;
    }


    
    /**
     * Get the value of resetToken
     */ 
    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    /**
     * Set the value of resetToken
     *
     * @return  self
     */ 
    public function setResetToken(?string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }


    /**
     * @return Collection<int, Devis>
     */
    public function getDevis(): Collection
    {
        return $this->devis;
    }

    public function addDevi(Devis $devi): static
    {
        if (!$this->devis->contains($devi)) {
            $this->devis->add($devi);
            $devi->setUser($this);
        }

        return $this;
    }

    public function removeDevi(Devis $devi): static
    {
        if ($this->devis->removeElement($devi)) {
            // set the owning side to null (unless already changed)
            if ($devi->getUser() === $this) {
                $devi->setUser(null);
            }
        }

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): static
    {
        $this->address = $address;

        return $this;
    }
    
    public function getIsVerified(): ?bool
    {
        return $this->is_verified;
    }

    public function setIsVerified(bool $is_verified): self
    {
        $this->is_verified = $is_verified;

        return $this;
    }


    public function getOperationEnCours(): ?int
    {
        return $this->operation_en_cours;
    }

    public function setOperationEnCours(?int $operation_en_cours): static
    {
        $this->operation_en_cours = $operation_en_cours;

        return $this;
    }

    /**
     * @return Collection<int, Operation>
     */
    public function getOperations(): Collection
    {
        return $this->operations;
    }

    public function addOperation(Operation $operation): static
    {
        if (!$this->operations->contains($operation)) {
            $this->operations->add($operation);
            $operation->setUser($this);

        }

        return $this;
    }

    public function removeOperation(Operation $operation): static
    {
        if ($this->operations->removeElement($operation)) {
            // set the owning side to null (unless already changed)
            if ($operation->getUser() === $this) {
                $operation->setUser(null);

            }
        }

        return $this;
    }


  
}

src/Form/CustomerType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\NotBlank;

class CustomerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email', EmailType::class, [
                'attr' => [
                    'class' => 'form-control'
                ],
                'label' => 'E-mail',
                'constraints' => [
                    new NotBlank(),
                    new Email(),
                ],
                'label_attr' => ['style' => 'margin-bottom: 3px;margin-top: 5px;'] // Ajouter une marge de 3px en bas pour le label
            ])
            ->add('roles', ChoiceType::class, [
                'choices'  => [
                    'ROLE_CLIENT' => 'ROLE_CLIENT',
                    'ROLE_USER' => 'ROLE_USER',
                ],
                'expanded' => false,
                'multiple' => false,
                'label' => 'Roles',
                'attr' => [
                    'class' => 'form-control'
                ],
                'label_attr' => ['style' => 'margin-bottom: 3px;margin-top: 5px;']
            ])
            ->add('lastname', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ],
                'label' => 'Nom',
                'label_attr' => ['style' => 'margin-bottom: 3px;margin-top: 5px;'] // Ajouter une marge de 3px en bas pour le label
            ])
            ->add('firstname', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ],
                'label' => 'Prénom',
                'label_attr' => ['style' => 'margin-bottom: 3px;margin-top: 5px;'] // Ajouter une marge de 3px en bas pour le label
            ])
            ->add('tel', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ],
                'label' => 'Téléphone',
                'label_attr' => ['style' => 'margin-bottom: 3px;margin-top: 5px;'] // Ajouter une marge de 3px en bas pour le label
            ])
            ->add('address', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ],
                'label' => 'Adresse',
                'label_attr' => ['style' => 'margin-bottom: 3px; margin-top 3pxmargin-top: 5px;'] // Ajouter une marge de 3px en bas pour le label
            ])
            ->get('roles')
            ->addModelTransformer(new CallbackTransformer(
                fn ($rolesAsArray) => count($rolesAsArray) ? $rolesAsArray[0] : null,
                fn ($rolesAsString) => [$rolesAsString]
            ));
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/Admin/CustomerController.php
<?php

namespace App\Controller\Admin;

use App\Entity\User;
use App\Form\UserType;
use App\Form\User1Type;
use App\Form\CustomerType;
use App\Service\JWTService;
use App\Service\SendMailService;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Doctrine\DBAL\Exception\UniqueConstraintViolationException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/admin/customer')]
class CustomerController extends AbstractController
{
    #[Route('/', name: 'app_customer_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        $roles = ['ROLE_CLIENT'];
        $customers = $userRepository->findByRoles($roles);

        return $this->render('admin/customer/index.html.twig', [
            'users' => $customers,
        ]);
    }

    #[Route('/new', name: 'app_customer_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager,SendMailService $mail, JWTService $jwt): Response
    {
        $user = new User();
        $user->setRoles(["ROLE_CLIENT"]);
        $form = $this->createForm(CustomerType::class, $user);
        $form->handleRequest($request);

        $error = null;

        if ($form->isSubmitted() && $form->isValid()) {
            try {$entityManager->persist($user);
                $entityManager->flush();
    
                $header =[
                    'typ'=>'JWT',
                    'alg'=>'HS256'
                ];

                $payload =[
                    'user_id'=>$user->getId()
                ];

                $token = $jwt->generate($header,$payload,
                $this->getParameter('app.jwtsecret'));
    
                $mail->send ('no-reply@cleanthis.fr',
                    $user->getEmail(),
                    'Activation de votre compte CleanThis',
                    'register',
                    compact('user','token')
                );
    
                return $this->redirectToRoute('app_customer_index', [], Response::HTTP_SEE_OTHER);
                
            } catch (UniqueConstraintViolationException $e) {
                if (str_contains($e->getMessage(), 'Duplicate entry') && str_contains($e->getMessage(), 'for key \'UNIQ_8D93D649E7927C74\'')) {
                    $error = 'L\'adresse e-mail existe déjà. Veuillez en choisir une autre.';
                }

            }
        }
    
        $this->denyAccessUnlessGranted('ROLE_APPRENTI');
    
        return $this->render('admin/customer/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
            'error' => $error, 
        ]);
    }




    #[Route('/{id}', name: 'app_customer_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('admin/customer/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_customer_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CustomerType::class, $user);
        $form->handleRequest($request);

        $error = null;
        
        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $entityManager->flush();

                return $this->redirectToRoute('app_customer_index', [], Response::HTTP_SEE_OTHER);
            } catch (UniqueConstraintViolationException $e) {

                if (str_contains($e->getMessage(), 'Duplicate entry') && str_contains($e->getMessage(), 'for key \'UNIQ_8D93D649E7927C74\'')) {

                    $error = 'L\'adresse e-mail existe déjà. Veuillez en choisir une autre.';
                }

            }
            
        }

        return $this->render('admin/customer/edit.html.twig', [
            'user' => $user,
            'form' => $form,
            'error' => $error
        ]);
    }

    #[Route('/{id}', name: 'app_customer_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $user->getId(), $request->request->get('_token'))) {
            $entityManager->remove($user);
            $entityManager->flush();

            return new JsonResponse(['success' => true]);
        }
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        return new JsonResponse(['success' => false]);
    }
}

templates/customer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}
{% block stylesheets %} 
   
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.22.3/dist/bootstrap-table.min.css">
    {# <link rel="stylesheet" href="public/assets/css/style.css"> #}
{% endblock %}

{% block body %}
   <section class="home">
    <div class="text">
    

  
    <h1>Liste des clients</h1>
    {# <a href="{{ path('app_user_new') }}" class="create"> + Ajouter un client</a> #}
{# {{% app.user.avatar %} #}

    <table class="table" data-toggle="table" data-search="true" data-show-columns="true" data-pagination="true">
        <thead class="en-tête">
            <tr>
                {# <th data-sortable="true" data-field="id">Id</th> #}
                {# <th data-sortable="true" data-field="email">Email</th> #}
                <th data-sortable="true" data-field="lastname" class="light-weight">Nom</th>
                <th data-sortable="true" data-field="firstname" class="light-weight">Prénom</th>
                <th data-sortable="true" data-field="roles" class="light-weight">Role</th>
                <th class="light-weight" >Avatar</th>
                {# <th data-sortable="true" data-field="address">Address</th> #}
                <th data-sortable="true" data-field="operation_finalisee" class="light-weight">Opérations finalisées</th>
                <th  class="light-weight">Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td  class="bold-weight">{{ user.lastname }}</td>
                <td class="bold-weight">{{ user.firstname }}</td>
                 <td>
                {% for role in user.roles %}
							{% if role == "ROLE_ADMIN" %}
								{% set name = "Administrateur" %}
								{% set color = "danger" %}
                            {% elseif  role == "ROLE_SENIOR"%}
                                {% set name = "Senior" %}
                                {% set color = "warning" %}
                            {% elseif  role == "ROLE_APPRENTI"%}
                                {% set name = "Apprenti" %}
                                {% set color = "primary" %}    
                                {% elseif  role == "ROLE_CLIENT"%}
                                {% set name = "Client" %}
                                {% set color = "secondary" %}       
							{% else %}
								{% set name = "Membre" %}
								{% set color = "success" %}
							{% endif %}
							<span class="badge bg-{{ color }}">{{ name }}</span>
						{% endfor %}
                </td>  
                <td><img src="{{user.avatar}}" style="height: 50px; border-radius: 6px; margin-left: 6px"></td>
                <td class="bold-weight">{{ user.operationsFinalisee }}</td>
                
                <td>
                    <a href="{{ path('app_customer_show', {'id': user.id}) }}" class ="actionsButtons1">Voir détail</a>
                    <a href="{{ path('app_customer_edit', {'id': user.id}) }}" class ="actionsButtons2">Modifier</a>
                    {# <a href="{{ path('app_user_delete', {'id': user.id})}}" class ="actionsButtons3">Supprimer</a> #}
                    <button class="btn deleteBtn actionsButtons3" id="delete{{ user.id }}" data-csrf-token="{{ csrf_token('delete' ~ user.id) }}">
							Supprimer
					</button>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="13">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

      </div>
   </section> 
{% endblock %}

{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.22.3/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.22.3/dist/bootstrap-table-fr-FR.min.js"></script>
   <script>
        $(document).ready(function() {

    $('.search input').attr('placeholder', 'Rechercher');
    $('.search input').addClass('form-control pr-5');
    $('.search').addClass('position-relative');
    $('.search input').after('<span id="searchIcon" class="input-group-text bi bi-search position-absolute" style="right: 10px; top: 28%; transform: translateY(-50%); cursor: pointer; border: none; padding: 0;"></span>');
    $('.search input').keydown(function(event) {
        if (event.keyCode === 13) { 
            $('#searchIcon').hide();
        }
    });
});

    </script>

    <script>
    $(document).ready(function() {
        $('.table').off('click', '.deleteBtn').on('click', '.deleteBtn', function(e) {
            e.preventDefault();
            var userId = this.id.replace('delete', '');
            var csrfToken = $(this).data('csrf-token');
            
            if (confirm('Êtes-vous sûr de vouloir supprimer cet utilisateur ?')) {
                $.ajax({
                    url: '/admin/customer/' + userId,
                    type: 'POST',
                    data: {
                        '_token': csrfToken,
                    },
                    success: function(response) {
                        if (response.success) {
                            alert("Utilisateur supprimé avec succès");
                            $('#delete' + userId).closest('tr').remove();
                            
                        location.reload();
                        
                        } else {
                            alert("La suppression a échoué");
                        }
                    },
                    error: function() {
                        alert("Une erreur s'est produite");
                    }
                });
            }
        });
    });
	</script>
    
{% endblock %}