src/Entity/Operation.php
<?php

namespace App\Entity;

use App\Entity\Trait\CreatedAtTrait;
use App\Entity\Trait\DateDebutTrait;
use App\Repository\OperationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OperationRepository::class)]
class Operation
{

    use DateDebutTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $facture = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $comment = null;

    #[ORM\Column(nullable: true)]
    private ?float $note = null;

    // #[ORM\Column]
    // private ?\DateTimeImmutable $date_debut = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $date_fin = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $image_resultat = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $reclamation = null;

    #[ORM\Column (options: ['default' => false])]
    private ?bool $status_paiement = false;

    #[ORM\Column (options: ['default' => false])]
    private ?bool $status_operation = false;


    #[ORM\ManyToMany(targetEntity: Devis::class, mappedBy: 'Operation')]
    private Collection $devis;

    #[ORM\ManyToOne(inversedBy: 'operations')]
    private ?User $user = null;

    public function __construct()
    {
        $this->devis = new ArrayCollection();
        $this->date_debut = new \DateTimeImmutable();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFacture(): ?string
    {
        return $this->facture;
    }

    public function setFacture(?string $facture): static
    {
        $this->facture = $facture;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): static
    {
        $this->comment = $comment;

        return $this;
    }

    public function getNote(): ?float
    {
        return $this->note;
    }

    public function setNote(?float $note): static
    {
        $this->note = $note;

        return $this;
    }

    // public function getDateDebut(): ?\DateTimeImmutable
    // {
    //     return $this->date_debut;
    // }

    // public function setDateDebut(\DateTimeImmutable $date_debut): static
    // {
    //     $this->date_debut = $date_debut;

    //     return $this;
    // }

    public function getDateFin(): ?\DateTimeImmutable
    {
        return $this->date_fin;
    }

    public function setDateFin(?\DateTimeImmutable $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getImageResultat(): ?string
    {
        return $this->image_resultat;
    }

    public function setImageResultat(?string $image_resultat): static
    {
        $this->image_resultat = $image_resultat;

        return $this;
    }

    public function getReclamation(): ?string
    {
        return $this->reclamation;
    }

    public function setReclamation(?string $reclamation): static
    {
        $this->reclamation = $reclamation;

        return $this;
    }

    public function isStatusPaiement(): ?bool
    {
        return $this->status_paiement;
    }

    public function setStatusPaiement(bool $status_paiement): static
    {
        $this->status_paiement = $status_paiement;

        return $this;
    }

    public function isStatusOperation(): ?bool
    {
        return $this->status_operation;
    }

    public function setStatusOperation(bool $status_operation): static
    {
        $this->status_operation = $status_operation;

        return $this;
    }

    /**
     * @return Collection<int, Devis>
     */
    public function getDevis(): Collection
    {
        return $this->devis;
    }

    public function addDevi(Devis $devi): static
    {
        if (!$this->devis->contains($devi)) {
            $this->devis->add($devi);
            $devi->addOperation($this);
        }

        return $this;
    }

    public function removeDevi(Devis $devi): static
    {
        if ($this->devis->removeElement($devi)) {
            $devi->removeOperation($this);
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

   
}

src/Controller/Client/CrudController.php
<?php

namespace App\Controller\Client;

use App\Entity\User;
use App\Entity\Devis;
use App\Form\DevisType;
use App\Form\ClientType;
use App\Entity\Operation;
use App\Service\PdfService;
use App\Entity\TypeOperation;
use App\Form\OperationNoteType;
use App\Form\ReclamationType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Doctrine\DBAL\Exception\UniqueConstraintViolationException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

#[Route('/user')]
class CrudController extends AbstractController
{

    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    #[Route('/profile', name: 'app_user_profil')]
    public function index(): Response
    {
        $user = $this->getUser();

        // Vérifie if the user is connected
        if ($user !== null) {
            //get the devis associate to the user
            $devis = $user->getDevis();

            // array to stock all the operations 
            $operations = [];

            // we get into each devis
            foreach ($devis as $devi) {
                // take all the operations associated with the devis
                $deviOperations = $devi->getOperation();
                
                // stock the operations in an array
                foreach ($deviOperations as $operation) {
                    $lastType = $devi->getTypeOperation();
                    $operations[] = [
                        'operation' => $operation,
                        'lastType' => $lastType,
                    ];
                }
            }

            // we send the operations to the view
            return $this->render('client/profil.html.twig', [
                'controller_name' => 'ClientController',
                'operations' => $operations,
                'devi' => $devis,
            ]);
        } else {
            // We are going to redirect to an error page
        }
    }

    #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ClientType::class, $user);
        $form->handleRequest($request);
        $user = $this->getUser();
        $error = null;

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $entityManager->flush();

                return $this->redirectToRoute('app_user_profil', [], Response::HTTP_SEE_OTHER);
            } catch (UniqueConstraintViolationException $e) {
                // Vérifier si le message d'erreur indique une violation de la contrainte d'unicité pour l'adresse e-mail
                if (str_contains($e->getMessage(), 'Duplicate entry') && str_contains($e->getMessage(), 'for key \'UNIQ_8D93D649E7927C74\'')) {
                    // Définir le message d'erreur approprié
                    $error = 'L\'adresse e-mail existe déjà. Veuillez en choisir une autre.';
                }
            }
        }
        return $this->render('client/edit_profil.html.twig', [
            'form' => $form,
        ]);

        // return $this->route('client/profil.html.twig', [
        //     'user' => $user,
        //     'form' => $form,
        //     'error' => $error
        // ]);
    }

    #[Route('/{id}/reclamation', name: 'app_operation_reclamation', methods: ['GET', 'POST'])]
    public function reclamation(Request $request, Operation $operation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ReclamationType::class, $operation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reclamation = $form->get('reclamation')->getData();
            $operation->setReclamation($reclamation);
            $entityManager->persist($operation);
            $entityManager->flush();
            return $this->render('client/success_reclamation.html.twig');
        }

        return $this->render('client/reclamation.html.twig', [
            'operation' => $operation,
            'form' => $form,
        ]);
    }

    #[Route("/uploads-avatar", name: "uploads_avatar", methods: ['POST'])]

    public function uploadAvatar(Request $request): Response
    {

        $file = $request->files->get('avatar');

        if ($file) {

            $fileName = md5(uniqid()) . '.' . $file->guessExtension();

            $directory = $this->getParameter('kernel.project_dir') . '/public/uploads/avatars';

            $file->move($directory, $fileName);

            $user = $this->getUser();
            $id = $this->getUser()->getId();

            $user->setAvatar('uploads/avatars/' . $fileName);

            $entityManager = $this->entityManager;
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('app_user_edit', [
                'id' => $id,
            ]);
        }
    }

    #[Route('/{id}/profile', name: 'app_profile_show', methods: ['GET'])]
    public function show(Operation $operation): Response
    {
        $user = $this->getUser();

        return $this->render('client/show.html.twig', [
            'operation' => $operation,
            'user' => $user,
        ]);
    }

    #[Route('/{id}/facture', name: 'app_operation_facture', methods: ['GET', 'POST'])]
    public function VoirFacture(PdfService $pdf, Operation $operation, UserRepository $userRepository, EntityManagerInterface $entityManager, Request $request): Response
    {
        $devis = $operation->getDevis()->first();

        if ($operation->isStatusOperation() && $devis) {

            $typeOperation = $devis->getTypeOperation(); // Récupérer l'entité TypeOperation à partir du devis

            $publicDirectory = $this->getParameter('kernel.project_dir') . '/public';
            $logoPath = $publicDirectory . '/images/logo.png';

            if (!file_exists($logoPath)) {
                throw new \Exception('Le fichier logo n\'existe pas.');
            }

            $logoData = base64_encode(file_get_contents($logoPath));
            $logoBase64 = 'data:image/png;base64,' . $logoData;

            $html = $this->renderView('Pdf/facture.html.twig', [
                'devi' => $devis,
                'type_operation' => $typeOperation,
                'logo_base64' => $logoBase64,
                'operation' => $operation
            ]);

            $pdfContent = $pdf->generateBinaryPDF($html);

            return new Response(
                $pdfContent,
                Response::HTTP_OK,
                [
                    'Content-Type' => 'application/pdf',
                    'Content-Disposition' => 'attachment; filename="facture.pdf"',
                ]
            );
        } else {
            $this->addFlash('warning', 'La facture n\'a pas pu être téléchargée');
            return $this->redirectToRoute('app_user_profil');
        }
    }

    #[Route('/devis', name: 'app_devis_client', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $devi = new Devis();
        $form = $this->createForm(DevisType::class, $devi);
        $form->handleRequest($request);
        $user = $this->getUser();
    
   
        if ($user) {
    
            $devi->setLastname($user->getLastname());
            $devi->setFirstname($user->getFirstname());
            $devi->setMail($user->getEmail());
            $devi->setTel($user->getTel());
            
            // Rendre les champs non modifiables
            $form = $this->createForm(DevisType::class, $devi, ['disabled_fields' => true]);
        } else {
            // Si l'utilisateur n'est pas connecté, créer un formulaire vide
            $form = $this->createForm(DevisType::class, $devi);
        }
        
        $form->handleRequest($request);

        // $type_operations = $entityManager->getRepository(TypeOperation::class)->findAll();

        if ($form->isSubmitted() && $form->isValid()) {

            $existingDevis = $entityManager->getRepository(Devis::class)->findOneBy([
                'mail' => $devi->getMail(),
                'typeOperation' => $devi->getTypeOperation(),
                'adresse_intervention' => $devi->getAdresseIntervention()
            ]);

            if ($existingDevis !== null) {
                $this->addFlash('warning', 'Ce devis existe déjà.');
                return $this->redirectToRoute('app_devis_client');
            }


            $serv = $form->getData();
            $mail = $form->get('mail')->getData();
            $mailConfirmation = $form->get('mailConfirmation')->getData();

            if ($mail === $mailConfirmation) {

                if($photo = $form['image_object']->getData()){
                    $fileName = uniqid().'.'.$photo->guessExtension();
                    $photo->move($this->getParameter('photo_dir'), $fileName);
                    $serv->setImageObject($fileName);
                }

                $typeOperation = $devi->getTypeOperation();
            if ($typeOperation !== null) {
                    $tarifTypeOperation = $typeOperation->getTarif();
                    $devi->setTarifCustom($tarifTypeOperation);
                }

                    $entityManager->persist($devi);
                    $entityManager->flush();
            }else { 
                $this->addFlash('warning', 'Les mails ne correspondent pas');
                return $this->redirectToRoute('app_devis_client', [], Response::HTTP_SEE_OTHER);
            };
            $this->addFlash('success', 'Devis envoyé avec succès.');

src/Controller/Client/DevisClientController.php
<?php

namespace App\Controller\Client;

use App\Entity\Devis;
use App\Entity\Operation;
use App\Entity\TypeOperation;
use App\Entity\User;
use App\Form\DevisType;
use App\Service\PdfService;
use App\Repository\UserRepository;
use App\Repository\DevisRepository;
use App\Service\JWTService;
use App\Service\SendMailService;
use Doctrine\ORM\EntityManagerInterface;
use PhpParser\Node\Stmt\Catch_;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Csrf\TokenGenerator\TokenGeneratorInterface;

#[Route('/devis')]
class DevisClientController extends AbstractController
{

    private EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

 

    #[Route('/', name: 'app_devis_client_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $devi = new Devis();
        $form = $this->createForm(DevisType::class, $devi);
        $form->handleRequest($request);

        // $type_operations = $entityManager->getRepository(TypeOperation::class)->findAll();

        if ($form->isSubmitted() && $form->isValid()) {

            $existingDevis = $entityManager->getRepository(Devis::class)->findOneBy([
                'mail' => $devi->getMail(),
                'typeOperation' => $devi->getTypeOperation(),
                'adresse_intervention' => $devi->getAdresseIntervention()
            ]);

            if ($existingDevis !== null) {
                $this->addFlash('danger', 'Ce devis existe déjà.');
                return $this->redirectToRoute('app_devis_client_new');
            }

            $serv = $form->getData();
            $mail = $form->get('mail')->getData();
            $mailConfirmation = $form->get('mailConfirmation')->getData();

            if ($mail === $mailConfirmation) {

                if($photo = $form['image_object']->getData()){
                    $fileName = uniqid().'.'.$photo->guessExtension();
                    $photo->move($this->getParameter('photo_dir'), $fileName);
                    $serv->setImageObject($fileName);
                }

                $typeOperation = $devi->getTypeOperation();
            if ($typeOperation !== null) {
                    $tarifTypeOperation = $typeOperation->getTarif();
                    $devi->setTarifCustom($tarifTypeOperation);
                }

                    $entityManager->persist($devi);
                    $entityManager->flush();
            }else { 
                $this->addFlash('danger', 'Les mails ne correspondent pas');
                return $this->redirectToRoute('app_devis_client_new', [], Response::HTTP_SEE_OTHER);
            };

            return $this->render('home/success_devis.html.twig');
        }

        return $this->render('home/devis.html.twig', [
            'devi' => $devi,
            'form' => $form,
        ]);
    }
}

templates/client/_form1.html.twig
{% block body %}
	<body
		style="background: #372772;">
		{# <section class="home1" style="background: #372772;"> #}
		<div class="container" style="padding-bottom: 30px;">
			<div class="row justify-content-center" style="background: #372772;">
				<div class="col-md-6 mt-5">
					<div class="headerDevis">
						<h2>{% trans %}Ask for a quote{% endtrans %}</h2>
						<p>{% trans %}Submit your quote request which will be analyzed by our team so that they can get back to you and arrange an appointment{% endtrans %}!</p>
					</div>
					<div class="card">
						<div class="card-bodyDevis">
							{{ form_start(form) }}
							<div class="row">
								<div class="col-md-6">
									{{ form_row(form.lastname) }}
								</div>
								<div class="col-md-6">
									{{ form_row(form.firstname) }}
								</div>
							</div>
							<div class="row">
								<div class="col-md-6">
									{{ form_row(form.mail) }}
								</div>
								<div class="col-md-6">
									{{ form_row(form.mailConfirmation) }}
								</div>
							</div>

							<div class="row">
								<div class="col-md-6">
									{{ form_row(form.tel) }}
								</div>
								<div class="col-md-6">
									{{ form_row(form.adresse_intervention, {'attr': {'class': 'form-control adresse-autocomplete', 'style': 'margin-top: 5px; margin-bottom: 5px;'}}) }}
								</div>
							</div>
							<div style="margin-left: 25%" class="col-md-6">
								<div class="operation">
									{{ form_row(form.Type_Operation) }}
								</div>
							</div>
							<div id="image-object-field" style="display: none;">
								{{ form_row(form.image_object) }}
							</div>
							{{ form_row(form.comment) }}

							<button class="btn btn-primary">{% trans %}Send quote{% endtrans %}</button>
							{{ form_end(form) }}

						</div>
					</div>
				</div>
			</div>
		</div>
		{# </section> #}
	</body>

	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script>
		$(document).ready(function () {
$('#image-object-field').hide();

$('.type-operation-select').change(function () {
console.log('Nouvelle valeur sélectionnée :', $(this).val());
var selectedOptionLabel = $(this).find('option:selected').text().toLowerCase();
var keyword = 'custom';
if (selectedOptionLabel.indexOf(keyword.toLowerCase()) !== -1) {
console.log('Option contenant "Custom" sélectionnée');
$('#image-object-field').show();
} else {
console.log('Autre option sélectionnée');
$('#image-object-field').hide();
}
});
});
	</script>
{% endblock %}
{% block javascripts %}
	{# <script>
		    document.addEventListener('DOMContentLoaded', function() {
		        var adresseInput = document.querySelector('.adresse-autocomplete');
		
		        if (!adresseInput) return;
		
		        function performSearchAndUpdateAdresse(query) {
		            var suggestionsContainer = document.createElement('div');
		            suggestionsContainer.className = 'suggestions-container';
		
		            fetch(`https://api-adresse.data.gouv.fr/search/?q=${encodeURIComponent(query)}&limit=5`)
		                .then(response => response.json())
		                .then(data => {
		                    suggestionsContainer.innerHTML = '';
		
		                    data.features.forEach((feature) => {
		                        var suggestion = document.createElement('div');
		                        suggestion.className = 'suggestion';
		                        suggestion.innerText = feature.properties.label;
		
		                        suggestion.addEventListener('click', function() {
		                            adresseInput.value = feature.properties.label;
		                            suggestionsContainer.innerHTML = '';
		                        });
		
		                        suggestionsContainer.appendChild(suggestion);
		                    });
		                })
		                .catch(error => console.error('Erreur API:', error));
		        }
		
		        // Écouter les événements de saisie sur le champ adresse_intervention
		        adresseInput.addEventListener('input', function() {
		            var query = adresseInput.value;
		            if (query.length < 3) return; // Éviter les requêtes trop fréquentes
		            performSearchAndUpdateAdresse(query);
		        });
		
		        adresseInput.parentNode.appendChild(suggestionsContainer);
		    });
		</script> #}

{% endblock %}

templates/client/devis.html.twig
{% extends 'basebis.html.twig' %}

{% block title %}New Devis
{% endblock %}
{% block stylesheets %}
	{{ parent() }}
	{# Inclut les feuilles de style du fichier parent #}
	<link rel="stylesheet" href="{{ asset('assets/css/devis.css') }}">
{% endblock %}

{% block body %}

	<div class='text2'>


		{{ include('client/_form1.html.twig') }}
		<a class="backtolist" href="{{ path('app_user_profil') }}"> &#8592; {% trans %}Back to profil{% endtrans %}</a>

	</div>
    <script src="{{ asset('assets/js/autocompleteDevis.js') }}"> defer</script>
{% endblock %}

templates/client/profil.html.twig
{% extends 'basebis.html.twig' %}

{% block title %}Mon profil Client
{% endblock %}
{% block stylesheets %}

	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
	<link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.22.3/dist/bootstrap-table.min.css">
	<link rel="stylesheet" href="{{asset('assets/css/client.css')}}">
{% endblock %}
{% block body  %}
	<section class="topBackground">
		<div class="animation">{% trans %}Your profil{% endtrans %}</div>
		<div class="animation">
			<span>{% trans %}CleanThis{% endtrans %}</span>
		</div>

	</section>
	<div class="personalInformations">

		<div class="personal">
			<strong>{{ app.user.lastname }}
				{{ app.user.firstname }}</strong>
			<p>{{ app.user.tel }}</p>
			<p>{{ app.user.email }}</p>
			<p>{{ app.user.address }}</p>
			{% if app.user.avatar == null %}
				<img src="{{ asset('images/avatar-placeholder.png') }}" alt="" class="avatar" width="150" height="150" style=" border-radius: 50%; object-fit: cover;">
			{% else %}
				<img src="{{ app.user.avatar ? asset(app.user.avatar) : 'placeholder.jpg' }}" alt="" class="avatar" width="140" height="140" style=" border-radius: 50%; object-fit: cover;">
			{% endif %}
		</div>
		<a href="{{ path('app_user_edit', {'id': app.user.id}) }}" class="ModifierInfos">{% trans %}Update my informations{% endtrans %}</a>
		<a href="{{ path('app_devis_client') }}" class="demanderDevis">{% trans %}Request a new quote{% endtrans %}</a>
	</div>
	<a href="#" id="scrollDownButton" class="scrollDownButton">{% trans %}See my operations{% endtrans %}
		&#8595;</a>
	<section class="homeProfil">
		<div class="text">
			<table class="table" data-toggle="table" data-search="true" data-show-columns="true" data-pagination="true">
				<thead class="en-tête">
					<tr>
						<th class="light-weight">{% trans %}Descriptive{% endtrans %}</th>
						<th data-sortable="true" data-field="date_debut" class="light-weight">{% trans %}Started on{% endtrans %}</th>
						<th data-sortable="true" data-field="date_fin" class="light-weight">{% trans %}Finished on{% endtrans %}</th>
						<th data-sortable="true" data-field="status_paiement" class="light-weight">{% trans %}Payment status{% endtrans %}</th>
						<th class="light-weight">{% trans %}View my invoice{% endtrans %}</th>
						<th class="light-weight">{% trans %}Leave a reclamation{% endtrans %}</th>
						<th class="light-weight">{% trans %}Rating us{% endtrans %}</th>

					</tr>
				</thead>
				<tbody>
					{% for item in operations %}
						{% set operation = item.operation %}
						{% set lastType = item.lastType.libelle  %}
						<tr>
							<td class="light-weight">{{ lastType }}</td>
							<td class="light-weight">{{ operation.dateDebut ? operation.dateDebut|date('Y-m-d H:i:s') : '' }}</td>
							<td class="light-weight">{{ operation.dateFin ? operation.dateFin|date('Y-m-d H:i:s') : '' }}</td>
							<td>
								{% if operation.statusPaiement %}
									<span style="color: green;" class="badge-success">{% trans %}Réglé
										<i style="color: green;" class='bx bx-check'></i>
										{% endtrans %}</span>
								{% else %}
									<a href="{{ path('payer', {'id': operation.id}) }}" style="background-color: #F2C57C; border:none; " class="btn btn-primary payer-facture">Payer ma facture</a>
								{% endif %}
							</td>

							<td>
								<a
									href="{{ path('app_operation_facture', {'id': operation.id}) }}" class="actionsButtons">
									{# <i class='bx bx-show'></i> #}
									<img src="{{ asset('images/pdf.png') }}" alt="">
								</a>
							</td>
							<td>
								{% if operation.reclamation %}
									<span style="color: green;">Envoyé <i style="color: green;" class='bx bx-check'></i></span>								
								{% else %}
									<a href="{{ path('app_operation_reclamation', {'id': operation.id}) }}" class="actionsButtons" style="text-decoration:none;">
										Reclamation
									</a>
								{% endif %}
							</td>
							<td>
								{% if operation.note %}
									<span style="color: green;">Envoyé <i style="color: green;" class='bx bx-check'></i></span>
								{% else %}
									<a href="{{ path('note', {'id': operation.id}) }}" style="text-decoration:none;">Laisser une note</a>
								{% endif %}
							</td>
						</tr>
					{% else %}
						<tr>
							<td colspan="13">{% trans %}no records found{% endtrans %}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>

		</div>
	</section>
{% endblock %}


{% block javascripts %}
	<script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>
	<script src="https://unpkg.com/bootstrap-table@1.22.3/dist/bootstrap-table.min.js"></script>
	<script src="https://unpkg.com/bootstrap-table@1.22.3/dist/bootstrap-table-fr-FR.min.js"></script>
	<script>
		$(document).ready(function () {

$('.search input').attr('placeholder', 'Rechercher ');
$('.search input').addClass('form-control pr-5');
$('.search').addClass('position-relative');
$('.search input').after('<span id="searchIcon" class="input-group-text bi bi-search position-absolute" style="right: 10px; top: 28%; transform: translateY(-50%); cursor: pointer; border: none; padding: 0;"></span>');
$('.search input').keydown(function (event) {
if (event.keyCode === 13) {
$('#searchIcon').hide();
}
});
});
	</script>

	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script>
		$(document).ready(function () {
$("#scrollDownButton").click(function () {
$('html, body').animate({
scrollTop: $(".homeProfil").offset().top
}, 1000);
});
});
	</script>

{% endblock %}

templates/client/show.html.twig
{% extends 'basebis.html.twig' %}

{% block title %}Operation
{% endblock %}

{% block body %}

	<h1>Operation</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Image_resultat</th>
				<td>{{ operation.imageResultat }}</td>
			</tr>
			<tr>
				<th>Status_paiement</th>
				<td>{{ operation.statusPaiement ? 'Yes' : 'No' }}</td>
			</tr>
		</tbody>
	</table>
	<a href="{{ path('app_operation_reclamation', {'id': operation.id}) }}" class="btn btn-primary laisser-reclamation">Laisser une réclamation</a>

	{% if operation.note is null %}
		<a href="{{ path('note', {'id': operation.id}) }}" class="btn btn-primary laisser-reclamation">Laisser une note</a>
	{% endif %}

	<a href="{{ path('app_user_profil') }}">back to list</a>

	{# <a href="{{ path('app_operation_edit', {'id': operation.id}) }}">edit</a> #}

	{# {{ include('operation/_delete_form.html.twig') }} #}
{% endblock %}